spring:
  application:
    name: xt-cloud-config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root
server:
  port: 8888
eureka:
  instance:
    nonSecurePort:  ${server.port}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      