server:
  port: 9999
spring:
  application:
    name: xt-zipkin
eureka:
  instance:
    nonSecurePort: ${server.port}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance-id:${server.port}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    lease:
      duration: 5
hystrix:
  command:
    pongCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      circuitBreaker:
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 2000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
