server:
  port: 8102
spring:
  application:
    name: xt-config-client             			#对应微服务配置文件名称
  cloud:
    config:
      uri: http://localhost:8101
      profile: dev                                      #项目配置文件选择
      label: master                                     #git仓库的分支
      discovery:
        enabled: true
        service-id: xt-cloud-config                  #config-server服务名称
      fail-fast: true             #失败快速响应
  rabbitmq:                    #本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    nonSecurePort:  ${server.port}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://xintu.eureka.com:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" #所有接口都暴露